apiVersion: v1
kind: PersistentVolume
metadata:
  name: retail-pv
spec: 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/general
    server: 13.126.251.60
